version: 2

sources:
  - name: adv_works
    database: FEA24_9  
    schema: raw_adventure_works  
    tables:
      - name: product
      - name: person
      - name: creditcard
      - name: specialoffer
      - name: salesorderheader